[package]
name = "wasm4-game"
version = "0.1.0"
authors = ["Piotr Merski <merskip@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[dependencies]
libm = "0.2"
